### PR TITLE
fix my mistakes and added mysql/mariadb creation back

### PR DESCRIPTION
**Pull request by Pr0mises**
I made some weird mistakes and somehow deleted the whole mysql creation in my last PR...

Also I tried to fix the mariadb/mysql detection. It's working like that for Debian12 but I'm pretty unsure if it's working like that for the other OS.

I already did multiple tests with debian11 and 12 and it randomly worked with the below if clauses but the output was pretty random for me... So ye I'm using the first one right now as it worked in Debian12. Prolly needs some more testing

```
if [[ -n "$(ps fax | grep 'mysqld' | grep -v 'grep')" || -n "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]]; then
	echo "jap"
else
	echo "Error1: No SQL server running but required for Webpanel installation."
fi

if [ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')"] || [ -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]; then
	echo "Error2: No SQL server running but required for Webpanel installation."
fi

if [[ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')" || -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]]; then
	echo "Error3: No SQL server running but required for Webpanel installation."
fi
```

### CODE REVIEW

**Comment by Nexus633** [comment]
The query is not there to check if MySQL exists. This query only checks whether a process is running. This is where the different expenses come from.

I would select it a little and then adapt it to the respective system using switch statements and functions.

This means you can check whether MySQL is installed on different systems. Furthermore, I am of the opinion that the MySQL package has been replaced with MariaDB and the mysql-server package is just a reference to maintain compatibility.

**Comment by Pr0mises** [comment]
> The query is not there to check if MySQL exists. This query only checks whether a process is running. This is where the different expenses come from.

I know that's what I check.


> I would select it a little and then adapt it to the respective system using switch statements and functions.

That should be the best option. My bash knowledge is limited amd I don't rly understand the difference between those 3 and why it doesn't detect it like it should.

> This means you can check whether MySQL is installed on different systems. Furthermore, I am of the opinion that the MySQL package has been replaced with MariaDB and the mysql-server package is just a reference to maintain compatibility.

Mostly yes, some ppl are still running mysql tho.

**Comment by Nexus633** [comment]
```sh
if [ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')"] || [ -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]; then
	echo "Error2: No SQL server running but required for Webpanel installation."
fi

if [[ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')" || -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]]; then
	echo "Error3: No SQL server running but required for Webpanel installation."
fi
```

is the same :-)

**Comment by Pr0mises** [comment]
> ```sh
> if [ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')"] || [ -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]; then
> 	echo "Error2: No SQL server running but required for Webpanel installation."
> fi
> 
> if [[ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')" || -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]]; then
> 	echo "Error3: No SQL server running but required for Webpanel installation."
> fi
> ```
> 
> is the same :-)

Not in my tests tho

**Comment by Nexus633** [comment]
use 

```sh
if [[ -n "$(ps aux | grep -v 'grep' | grep -E 'mysqld|mariadb')" ]]; then
	echo "jap"
else
	echo "Error1: No SQL server running but required for Webpanel installation."
fi
```

you dont need more if statements.

```sh
if [ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')"] || [ -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]; then
	echo "Error2: No SQL server running but required for Webpanel installation."
fi

if [[ -z "$(ps fax | grep 'mysqld' | grep -v 'grep')" || -z "$(ps fax | grep 'mariadb' | grep -v 'grep')" ]]; then
	echo "Error3: No SQL server running but required for Webpanel installation."
fi
```

Use the -z parameter to check whether the output is empty. Since the first query mysqld is empty, the if statement is true. The second query is not carried out at all because there is an 'or ||' operator is.

The same applies to the other statement. Therefore they are the same!

In your first query, use -n to check whether the output contains content. Since this is also true in the first case, the 'odeer ||' also occurs here. not a. However, if mariadb is installed, the 'or ||' queried. In this case it is 'or ||' true.

I hope I explained it clearly.

**Comment by Pr0mises** [comment]
Yes that makes sense just the behaviour it tested not. Even though I used -n in the code so it should work now

**Comment by Nexus633** [comment]
Now that we've clarified that, I wanted to raise an objection to the pull. I just tried the installer and it works perfectly. I see that not many changes have been made, only string conversions have been replaced.

I see no reason to confirm and merge this pull. Can you briefly explain that to me?

**Comment by Pr0mises** [comment]
Did you use this PR or dev version of the installer? If the dev version there is no database created as I accidentally deleted it in my last PR. I also added some fixes to the ssh keygen, as well as a check for sudo

**Comment by Nexus633** [comment]
Ah, I saw the errors. I agree with the pull and merge this.

No, I didn't use the pull. I use ddev in my environment to use a full environment with little effort. I also always install by hand. That's why I didn't notice it. When I look closely at the pull, I agree with you that there are a few errors in it that I wouldn't have noticed until late in the process.

Please write exactly what you did next time you pull. Try to write the pulls as if the other person was completely ignorant. This simplifies a lot and leaves little demand.

Thank you for your pull

**Pull request merged**
